server:
    port: 8888

spring:
    application:
        name: config-service
    cloud:
        config:
            server:
                native:
                    search-locations: file:../../../../infra/config-repo

eureka:
    client:
        register-with-eureka: true
        fetch-registry: true
        service-url:
            defaultZone: http://discovery-service:8761/eureka/