server:
    port: 8888

spring:
    application:
        name: config-service

eureka:
    client:
        register-with-eureka: true
        fetch-registry: true
        service-url:
            defaultZone: http://discovery-service:8761/eureka/